name: Deploy Telepoop Backend

on: [push]

env:
  AWS_REGION: us-west-2
  SECURITY_TOKEN_SECRET: ${{ secrets.SECURITY_TOKEN_SECRET }}
  DEPLOYMENT_BUCKET: ${{ secrets.DEPLOYMENT_BUCKET }}
  OUTPUT_TEMPLATE_FILE: sam-packaged.yaml
  STACK_NAME: telepoop-backend-stack
  TELEPOOP_APP_CLIENT: ${{ secrets.TELEPOOP_APP_CLIENT }}
  USERS_TABLE: ${{ secrets.USERS_TABLE }}

jobs:
  Deploy-AWS:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'
      - run: ls -R
      - name: Add secrets to Chalice app
        run: python add_secrets_to_chalice.py
      - name: Deploy telepoop
        working-directory: telepoop-backend
        run: |
          pip install -r ./requirements.txt
          chalice package ./packages
          aws cloudformation package --template-file ./packages/sam.json --s3-bucket ${{ secrets.DEPLOYMENT_BUCKET }} --output-template-file ${{ env.OUTPUT_TEMPLATE_FILE }}
          aws cloudformation deploy --template-file ${{ env.OUTPUT_TEMPLATE_FILE }} --stack-name ${{ env.STACK_NAME }} --capabilities CAPABILITY_IAM
